spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/opshub}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME:opshub}
spring.datasource.password=${DATABASE_PASSWORD}

spring.h2.console.enabled=false
opshub.security.password=${OPSHUB_SECURITY_PASSWORD}
