CREATE TABLE IF NOT EXISTS iot_energy_staging (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_day DATE NOT NULL,
    shift_name VARCHAR(20) NOT NULL,
    machine_code VARCHAR(40) NOT NULL,
    production_line VARCHAR(40) NOT NULL,
    energy_kwh DECIMAL(12, 2) NOT NULL,
    produced_units INTEGER NOT NULL
);

CREATE OR REPLACE VIEW rpt_issue_aging AS
SELECT
    pi.id AS issue_id,
    pi.title,
    pi.status,
    pi.severity,
    pi.category,
    pi.assigned_team,
    COALESCE(m.code, 'NO-MACHINE') AS machine_code,
    COALESCE(pl.code, 'NO-LINE') AS production_line,
    wo.sap_order_number,
    pi.created_at,
    pi.resolved_at,
    DATEDIFF('HOUR', pi.created_at, COALESCE(pi.resolved_at, CURRENT_TIMESTAMP)) AS age_hours,
    CASE WHEN pi.status IN ('RESOLVED', 'VERIFIED') THEN 0 ELSE 1 END AS open_flag,
    pi.downtime_minutes
FROM production_issue pi
LEFT JOIN machine m ON pi.machine_id = m.id
LEFT JOIN production_line pl ON m.production_line_id = pl.id
LEFT JOIN work_order wo ON pi.work_order_id = wo.id;

CREATE OR REPLACE VIEW rpt_downtime_by_machine AS
SELECT
    COALESCE(m.code, 'NO-MACHINE') AS machine_code,
    COALESCE(m.name, 'No machine assigned') AS machine_name,
    COALESCE(pl.code, 'NO-LINE') AS production_line,
    COUNT(pi.id) AS issue_count,
    SUM(pi.downtime_minutes) AS downtime_minutes,
    SUM(CASE WHEN pi.status IN ('RESOLVED', 'VERIFIED') THEN 0 ELSE 1 END) AS open_issue_count,
    MAX(pi.created_at) AS last_issue_at
FROM production_issue pi
LEFT JOIN machine m ON pi.machine_id = m.id
LEFT JOIN production_line pl ON m.production_line_id = pl.id
GROUP BY COALESCE(m.code, 'NO-MACHINE'), COALESCE(m.name, 'No machine assigned'), COALESCE(pl.code, 'NO-LINE');

CREATE OR REPLACE VIEW rpt_oee_daily AS
SELECT
    CAST(pi.created_at AS DATE) AS report_date,
    COALESCE(pl.code, 'NO-LINE') AS production_line,
    COUNT(pi.id) AS issue_count,
    SUM(pi.downtime_minutes) AS downtime_minutes,
    ROUND((480 - LEAST(480, SUM(pi.downtime_minutes))) * 100.0 / 480, 1) AS availability_proxy_percent,
    ROUND(((480 - LEAST(480, SUM(pi.downtime_minutes))) * 100.0 / 480) * 0.92 * 0.96, 1) AS oee_proxy_percent
FROM production_issue pi
LEFT JOIN machine m ON pi.machine_id = m.id
LEFT JOIN production_line pl ON m.production_line_id = pl.id
GROUP BY CAST(pi.created_at AS DATE), COALESCE(pl.code, 'NO-LINE');

CREATE OR REPLACE VIEW rpt_energy_per_unit AS
SELECT
    reading_day AS report_date,
    shift_name,
    machine_code,
    production_line,
    SUM(energy_kwh) AS total_energy_kwh,
    SUM(produced_units) AS produced_units,
    ROUND(SUM(energy_kwh) / NULLIF(SUM(produced_units), 0), 3) AS energy_kwh_per_unit
FROM iot_energy_staging
GROUP BY reading_day, shift_name, machine_code, production_line;
