CREATE TABLE IF NOT EXISTS production_line (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255),
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS machine (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255),
    criticality VARCHAR(255),
    name VARCHAR(255),
    production_line_id INTEGER NOT NULL,
    CONSTRAINT fk_machine_production_line FOREIGN KEY (production_line_id) REFERENCES production_line (id)
);

CREATE TABLE IF NOT EXISTS work_order (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    due_date TIMESTAMP(6) WITH TIME ZONE,
    material_code VARCHAR(255),
    material_description VARCHAR(255),
    planned_quantity INTEGER NOT NULL,
    sap_order_number VARCHAR(255),
    status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS production_issue (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assigned_team VARCHAR(255),
    assigned_to VARCHAR(255),
    category VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE,
    description VARCHAR(1200),
    downtime_minutes INTEGER NOT NULL,
    notification_channel VARCHAR(255),
    resolved_at TIMESTAMP(6) WITH TIME ZONE,
    severity VARCHAR(255),
    source VARCHAR(255),
    status VARCHAR(255),
    title VARCHAR(255),
    machine_id INTEGER,
    work_order_id INTEGER,
    CONSTRAINT fk_production_issue_machine FOREIGN KEY (machine_id) REFERENCES machine (id),
    CONSTRAINT fk_production_issue_work_order FOREIGN KEY (work_order_id) REFERENCES work_order (id)
);

CREATE TABLE IF NOT EXISTS issue_activity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(255),
    message VARCHAR(1200),
    type VARCHAR(255),
    production_issue_id INTEGER NOT NULL,
    CONSTRAINT fk_issue_activity_production_issue FOREIGN KEY (production_issue_id) REFERENCES production_issue (id)
);

CREATE TABLE IF NOT EXISTS issue_attachment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(255),
    file_name VARCHAR(255),
    relative_path VARCHAR(255),
    stored_file_name VARCHAR(255),
    uploaded_at TIMESTAMP(6) WITH TIME ZONE,
    production_issue_id INTEGER NOT NULL,
    CONSTRAINT fk_issue_attachment_production_issue FOREIGN KEY (production_issue_id) REFERENCES production_issue (id)
);

CREATE TABLE IF NOT EXISTS iot_machines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    ideal_energy_per_unit DOUBLE PRECISION NOT NULL,
    line_name VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    target_cycle_time DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS iot_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_time DOUBLE PRECISION NOT NULL,
    energy_kwh DOUBLE PRECISION NOT NULL,
    error_code VARCHAR(40),
    produced_units INTEGER NOT NULL,
    recorded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    shift_name VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    temperature DOUBLE PRECISION NOT NULL,
    vibration DOUBLE PRECISION NOT NULL,
    machine_id INTEGER NOT NULL,
    CONSTRAINT fk_iot_telemetry_machine FOREIGN KEY (machine_id) REFERENCES iot_machines (id)
);

CREATE TABLE IF NOT EXISTS iot_anomalies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_open BOOLEAN NOT NULL,
    kind VARCHAR(60) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    recorded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    severity VARCHAR(20) NOT NULL,
    threshold DOUBLE PRECISION,
    measured_value DOUBLE PRECISION,
    machine_id INTEGER NOT NULL,
    telemetry_id BIGINT NOT NULL,
    CONSTRAINT fk_iot_anomaly_machine FOREIGN KEY (machine_id) REFERENCES iot_machines (id),
    CONSTRAINT fk_iot_anomaly_telemetry FOREIGN KEY (telemetry_id) REFERENCES iot_telemetry (id)
);

CREATE TABLE IF NOT EXISTS iot_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    is_open BOOLEAN NOT NULL,
    message VARCHAR(1000) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    title VARCHAR(160) NOT NULL,
    anomaly_id BIGINT,
    machine_id INTEGER NOT NULL,
    CONSTRAINT fk_iot_alert_anomaly FOREIGN KEY (anomaly_id) REFERENCES iot_anomalies (id),
    CONSTRAINT fk_iot_alert_machine FOREIGN KEY (machine_id) REFERENCES iot_machines (id)
);

CREATE TABLE IF NOT EXISTS iot_energy_staging (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_day DATE NOT NULL,
    shift_name VARCHAR(20) NOT NULL,
    machine_code VARCHAR(40) NOT NULL,
    production_line VARCHAR(40) NOT NULL,
    energy_kwh DECIMAL(12, 2) NOT NULL,
    produced_units INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_production_issue_created_at ON production_issue (created_at);
CREATE INDEX IF NOT EXISTS idx_production_issue_status ON production_issue (status);
CREATE INDEX IF NOT EXISTS idx_iot_telemetry_machine_recorded_at ON iot_telemetry (machine_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_iot_anomalies_open_recorded_at ON iot_anomalies (is_open, recorded_at);
CREATE INDEX IF NOT EXISTS idx_iot_alerts_open_created_at ON iot_alerts (is_open, created_at);
